import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react'

type ReactiveFrame = { normalizedBass:number; normalizedMid:number; normalizedTreble:number; overallEnergy:number; isPlaying:boolean; spectrum:number[]; supported:boolean }
type ReactiveEngine = ReactiveFrame & { attach:(element:HTMLAudioElement)=>void; resume:()=>void }
const EMPTY:ReactiveFrame={normalizedBass:0,normalizedMid:0,normalizedTreble:0,overallEnergy:0,isPlaying:false,spectrum:Array.from({length:18},()=>0),supported:true}
const FrameContext=createContext<ReactiveFrame|null>(null)
const EngineContext=createContext<Pick<ReactiveEngine,'attach'|'resume'>|null>(null)
const clamp=(value:number)=>Math.max(0,Math.min(1,value))

export function AudioReactiveProvider({children}:{children:ReactNode}){
 const [frame,setFrame]=useState<ReactiveFrame>(EMPTY)
 const contextRef=useRef<AudioContext|null>(null),analyserRef=useRef<AnalyserNode|null>(null),dataRef=useRef<Uint8Array<ArrayBuffer>|null>(null),rafRef=useRef<number|null>(null)
 const sourcesRef=useRef(new Map<HTMLAudioElement,MediaElementAudioSourceNode>()),listenersRef=useRef(new Map<HTMLAudioElement,()=>void>()),smoothRef=useRef({bass:0,mid:0,treble:0,energy:0}),lastPublishRef=useRef(0)
 const ensureContext=useCallback(()=>{if(contextRef.current)return contextRef.current;const AudioContextClass=window.AudioContext??(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioContextClass){setFrame(value=>({...value,supported:false}));return null}const context=new AudioContextClass(),analyser=context.createAnalyser();analyser.fftSize=256;analyser.smoothingTimeConstant=.72;analyser.connect(context.destination);contextRef.current=context;analyserRef.current=analyser;dataRef.current=new Uint8Array(analyser.frequencyBinCount);return context},[])
 const tick=useCallback((now:number)=>{const analyser=analyserRef.current,data=dataRef.current;if(!analyser||!data)return;analyser.getByteFrequencyData(data);const hzPerBin=(contextRef.current?.sampleRate??44100)/analyser.fftSize;const average=(fromHz:number,toHz:number)=>{const from=Math.max(0,Math.floor(fromHz/hzPerBin)),to=Math.min(data.length,Math.ceil(toHz/hzPerBin));let sum=0;for(let i=from;i<to;i++)sum+=data[i];return to>from?sum/(to-from)/255:0};const playing=[...sourcesRef.current.keys()].some(audio=>!audio.paused&&!audio.ended);const target=playing?{bass:average(20,250),mid:average(250,4000),treble:average(4000,12000)}:{bass:0,mid:0,treble:0};const smooth=smoothRef.current,factor=playing?.2:.16;smooth.bass+=(target.bass-smooth.bass)*factor;smooth.mid+=(target.mid-smooth.mid)*factor;smooth.treble+=(target.treble-smooth.treble)*factor;const energy=target.bass*.45+target.mid*.38+target.treble*.17;smooth.energy+=(energy-smooth.energy)*factor;if(now-lastPublishRef.current>32){const spectrum=Array.from({length:18},(_,index)=>{const start=Math.floor(index*data.length/18),end=Math.max(start+1,Math.floor((index+1)*data.length/18));let sum=0;for(let cursor=start;cursor<end;cursor++)sum+=data[cursor];return clamp(sum/(end-start)/255)});setFrame({normalizedBass:clamp(smooth.bass),normalizedMid:clamp(smooth.mid),normalizedTreble:clamp(smooth.treble),overallEnergy:clamp(smooth.energy),isPlaying:playing,spectrum,supported:true});lastPublishRef.current=now}rafRef.current=requestAnimationFrame(tick)},[])
 const resume=useCallback(()=>{const context=ensureContext();if(!context)return;void context.resume();if(rafRef.current===null)rafRef.current=requestAnimationFrame(tick)},[ensureContext,tick])
 const attach=useCallback((element:HTMLAudioElement)=>{if(sourcesRef.current.has(element))return;const context=ensureContext(),analyser=analyserRef.current;if(!context||!analyser)return;try{const source=context.createMediaElementSource(element);source.connect(analyser);sourcesRef.current.set(element,source);const sync=()=>setFrame(value=>({...value,isPlaying:[...sourcesRef.current.keys()].some(audio=>!audio.paused&&!audio.ended)}));element.addEventListener('play',sync);element.addEventListener('pause',sync);element.addEventListener('ended',sync);listenersRef.current.set(element,()=>{element.removeEventListener('play',sync);element.removeEventListener('pause',sync);element.removeEventListener('ended',sync)})}catch{setFrame(value=>({...value,supported:false}))}},[ensureContext])
 useEffect(()=>()=>{if(rafRef.current!==null)cancelAnimationFrame(rafRef.current);listenersRef.current.forEach(cleanup=>cleanup());sourcesRef.current.forEach(source=>source.disconnect());analyserRef.current?.disconnect();void contextRef.current?.close()},[])
 const engine=useMemo(()=>({attach,resume}),[attach,resume]);return <EngineContext.Provider value={engine}><FrameContext.Provider value={frame}>{children}</FrameContext.Provider></EngineContext.Provider>
}
export function useAudioReactive():ReactiveFrame{const value=useContext(FrameContext);if(!value)throw new Error('useAudioReactive 必须放在 AudioReactiveProvider 内');return value}
export function useAudioReactiveEngine():Pick<ReactiveEngine,'attach'|'resume'>{const value=useContext(EngineContext);if(!value)throw new Error('useAudioReactiveEngine 必须放在 AudioReactiveProvider 内');return value}
