import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Avatar } from '../components/Avatar'
import { BellIcon, SparkleIcon, UsersIcon } from '../components/icons'
import { useSocial, type Thread } from '../store/social'

export function MessagesPage(){
 const navigate=useNavigate(),{threads}=useSocial();const [filter,setFilter]=useState('全部');const waiting=false
 const visible=[...threads].sort((a,b)=>(a.kind==='agent'?-1:a.kind==='system'?1:0)-(b.kind==='agent'?-1:b.kind==='system'?1:0)).filter(t=>filter==='全部'||(filter==='通知'?t.kind==='system':t.kind==='agent'))
 return <div className='summer-account-page' data-page='messages'><header className='summer-heading'><span className='summer-eyebrow'>QQ音乐 · 一起去现场</span><h1>消息</h1><p>今晚，有人正在回应你的同频</p></header>
  <section className='summer-glass invitation-feature'><span className='invitation-sun' aria-hidden='true'>☀</span><div className='invitation-top'><span className='invitation-orbits'><img src={import.meta.env.BASE_URL+'portraits/demo-orange.webp'} alt='Demo访客头像'/><Avatar name='同频听众' from='#8d72ff' to='#283865' size={46}/></span><span className='summer-pill'>{waiting?'等待对方确认':'邀请样式 · Demo'}</span></div><h2>{waiting?'1个同频邀请待确认':'有一封同频邀请正在等你'}</h2><p>共同歌曲《烟花》 · 夜航计划</p><button className='summer-primary' onClick={()=>navigate('/concert/night-voyage/sync/reveal')}>{waiting?'查看邀请':'拆开邀请'} <span>›</span></button>{!waiting&&<small>展示示例，不代表已收到真人邀请</small>}</section>
  <div className='summer-filters' aria-label='消息分类'>{['全部','同频邀请','通知'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><section aria-label='会话列表' className='summer-thread-list'>{visible.map(thread=><ThreadRow key={thread.id} thread={thread} onOpen={()=>navigate(thread.kind==='group'&&thread.concertId?'/concert/'+thread.concertId+'/room':'/messages/'+thread.id)}/>)}</section><p className='summer-disclaimer'>赛事 Demo · 会话为模拟数据，未接入官方账号</p></div>
}
function ThreadRow({thread,onOpen}:{thread:Thread;onOpen:()=>void}){const {messagesOf,unreadOf,roomChatOf}=useSocial(),room=roomChatOf(thread.id),preview=room?.preview||messagesOf(thread.id).slice(-1)[0]?.text||thread.subtitle;return <button onClick={onOpen} className={'summer-thread '+(thread.kind==='agent'?'pinned-thread ':'')+(thread.kind==='system'?'system-thread':'')}>{thread.avatar?<Avatar name={thread.title} from={thread.avatar.from} to={thread.avatar.to} size={48}/>:<span className='summer-thread-icon'>{thread.kind==='agent'?<SparkleIcon/>:thread.kind==='system'?<BellIcon/>:<UsersIcon/>}</span>}<span className='summer-thread-copy'><strong>{thread.kind==='agent'?'音乐助手':thread.title}</strong><span className='summer-thread-label'>{thread.kind==='agent'?'置顶 · 你的同行助手':thread.kind==='system'?'活动提醒':room?.meetingLabel||thread.statusLabel||'夜航计划'}</span><span className='summer-preview'>{preview}</span></span><span className='summer-thread-meta'><time>{room?.time||thread.time}</time>{unreadOf(thread)>0&&<span className='summer-unread' aria-label='未读消息'/>}</span></button>}
