import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Avatar } from '../components/Avatar'
import { BellIcon, SparkleIcon, UsersIcon } from '../components/icons'
import { useSocial, type Thread } from '../store/social'
import { useSession } from '../store/session'

export function MessagesPage(){
 const navigate=useNavigate(),{threads}=useSocial();const { agent, room } = useSession();const [filter,setFilter]=useState('全部')
 const accepted = Boolean(room || agent?.roomId || agent?.pendingConfirmation?.status === 'accepted' || agent?.pendingConfirmation?.status === 'both_confirmed')
 const waiting = !accepted && agent?.pendingConfirmation?.status === 'awaiting_peer'
 const visible=[...threads].sort((a,b)=>(a.kind==='agent'?-1:a.kind==='system'?1:0)-(b.kind==='agent'?-1:b.kind==='system'?1:0)).filter(t=>filter==='全部'||(filter==='通知'?t.kind==='system':t.kind==='agent'))
 return <div className='summer-account-page' data-page='messages'><header className='summer-heading'><button type='button' className='summer-back-link' aria-label='返回首页' onClick={()=>navigate('/home')}>← 首页</button><span className='summer-eyebrow'>QQ音乐 · 一起去现场</span><h1>消息</h1><p>今晚，你的同行伙伴已就位</p></header>
  {waiting ? <section className='summer-glass invitation-feature'><span className='invitation-sun' aria-hidden='true'>☀</span><div className='invitation-top'><span className='invitation-orbits'><img src={import.meta.env.BASE_URL+'avatars/candidate-orange.webp'} alt='靠近舞台的橘子'/><Avatar name='同频听众' from='#8d72ff' to='#283865' size={46}/></span><span className='summer-pill'>等待对方确认</span></div><h2>有一封同频邀请正在等你</h2><p>共同歌曲《烟花》 · 夜航计划</p><button className='summer-primary' onClick={()=>navigate('/concert/night-voyage/sync/reveal')}>拆开邀请 <span>›</span></button></section> : accepted ? <section className='summer-glass invitation-feature'><span className='invitation-sun' aria-hidden='true'>♪</span><h2>夜航计划同行组 · 3 人集合中</h2><p>已确认集合点 18:50 · 共同歌曲《烟花》</p><button className='summer-primary' onClick={()=>navigate('/concert/night-voyage/room')}>进入同行组 <span>›</span></button></section> : null}
  <div className='summer-filters' aria-label='消息分类'>{['全部','同频邀请','通知'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><section aria-label='会话列表' className='summer-thread-list'>{visible.map(thread=><ThreadRow key={thread.id} thread={thread} onOpen={()=>navigate(thread.kind==='group'?'/concert/night-voyage/room':'/messages/'+thread.id)}/>)}</section><p className='summer-disclaimer'>会话已同步 · 仅展示本次同频相关信息</p></div>
}
function ThreadRow({thread,onOpen}:{thread:Thread;onOpen:()=>void}){const {messagesOf,unreadOf,roomChatOf}=useSocial(),room=roomChatOf(thread.id),preview=room?.preview||messagesOf(thread.id).slice(-1)[0]?.text||thread.subtitle;return <button onClick={onOpen} className={'summer-thread '+(thread.kind==='agent'?'pinned-thread ':'')+(thread.kind==='system'?'system-thread':'')}>{thread.avatar?<Avatar name={thread.title} from={thread.avatar.from} to={thread.avatar.to} size={48}/>:<span className='summer-thread-icon'>{thread.kind==='agent'?<SparkleIcon/>:thread.kind==='system'?<BellIcon/>:<UsersIcon/>}</span>}<span className='summer-thread-copy'><strong>{thread.kind==='agent'?'音乐助手':thread.title}</strong><span className='summer-thread-label'>{thread.kind==='agent'?'置顶 · 你的同行助手':thread.kind==='system'?'活动提醒':room?.meetingLabel||thread.statusLabel||'夜航计划'}</span><span className='summer-preview'>{preview}</span></span><span className='summer-thread-meta'><time>{room?.time||thread.time}</time>{unreadOf(thread)>0&&<span className='summer-unread' aria-label='未读消息'/>}</span></button>}
