import { useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Avatar } from '../components/Avatar'
import { PageShell } from '../components/PageShell'
import { AlertIcon, CheckIcon, ClockIcon, MapPinIcon, MusicIcon, ShieldIcon, UsersIcon } from '../components/icons'
import { Button, Card, DemoBadge, SectionTitle, Sheet, StateView } from '../components/ui'
import { UserAvatar } from '../components/UserAvatar'
import { useProfile } from '../store/profile'
import { useSession } from '../store/session'

type ChatMessage = { id: string; userId: string; nickname: string; text: string; time: string; mine?: boolean; system?: boolean }
const PRESET: ChatMessage[] = [
  { id: 'safety', userId: 'system', nickname: '系统安全提示', system: true, time: '18:31', text: '同行Agent已完成安全条件核对。请勿发送身份证、票务验证码、精确住址等敏感信息。' },
  { id: 'm1', userId: 'mock-muna', nickname: '木那啦啦', time: '18:33', text: '我大概18:40到，可以先在检票口附近等大家～' },
  { id: 'm2', userId: 'mock-jiangli', nickname: '写歌的江离', time: '18:34', text: '好呀，我穿蓝色外套，到时候在群里说一声。' },
]
const QUICK_REPLIES = ['我也差不多 18:40 到', '收到，到了群里说', '我们在公开集合点见']
const REPORT_REASONS = ['包含敏感信息', '骚扰或不当言论', '诱导私下转账', '其他原因']

export function RoomPage() {
  const { concertId = '' } = useParams(); const navigate = useNavigate()
  const { room, roomError, toggleTask, toggleMemberConfirm, confirmMeeting, leaveRoom, report, pushToast, agent } = useSession()
  // 当前用户（我）的昵称与头像统一来自 profile store，禁止在页面里另存一份
  const { profile } = useProfile()
  const [exitOpen, setExitOpen] = useState(false); const [reportMessage, setReportMessage] = useState<ChatMessage | null>(null)
  const [reportReason, setReportReason] = useState(''); const [tasksOpen, setTasksOpen] = useState(false)
  const [input, setInput] = useState(''); const [blocked, setBlocked] = useState<string[]>([]); const [messages, setMessages] = useState<ChatMessage[]>([])
  const inputRef = useRef<HTMLInputElement>(null); const storageKey = `syncstage.chat.${room?.roomId ?? concertId}`
  useEffect(() => { if (!room) return; try { setMessages(JSON.parse(localStorage.getItem(storageKey) || 'null') || PRESET) } catch { setMessages(PRESET) } }, [room, storageKey])
  useEffect(() => { if (room && messages.length) localStorage.setItem(storageKey, JSON.stringify(messages)) }, [messages, room, storageKey])

  if (!room) { const pending = agent?.pendingConfirmation; return <PageShell title='同频临时房间' step={3} onBack={() => navigate(`/concert/${concertId}/matches`)}><div className='flex flex-col gap-4'><Card><p className='text-sm text-brand-200'>等待全部成员确认，确认完成后开放临时群聊。</p><p className='mt-2 text-sm text-white/50'>当前状态：{pending?.status === 'awaiting_peer' ? '等待对方确认' : '尚未完成邀请'}。</p></Card>{roomError ? <StateView status='error' title='房间没有准备好' description={roomError} /> : null}<StateView status='empty' title='回到匹配结果完成双向确认' actionLabel='回到匹配结果' onAction={() => navigate(`/concert/${concertId}/matches`)}/></div></PageShell> }

  const confirmedCount = room.members.filter((m) => m.confirmed).length, allConfirmed = confirmedCount === room.members.length
  const archived = Date.now() >= room.createdAt + 24 * 60 * 60 * 1000
  const visibleMessages = messages.filter((m) => !blocked.includes(m.userId)), tasks = room.tasks ?? [], doneCount = tasks.filter((t) => t.done).length
  const send = () => { const text = input.trim(); if (!allConfirmed || archived || !text) return; setMessages((prev) => [...prev, { id: `local-${Date.now()}`, userId: 'me', nickname: profile.nickname, text, time: new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit', hour12: false }), mine: true }]); setInput(''); inputRef.current?.focus() }
  const icebreaker = () => { if (!allConfirmed || archived) return; setInput(room.icebreakers[0] || '你最期待今晚现场的哪一首歌？'); pushToast('AI 破冰建议已填入输入框，请确认后再发送'); inputRef.current?.focus() }

  const footer = allConfirmed ? <div className='pb-1'>{archived ? <p className='py-3 text-center text-sm text-white/50'>房间已归档，只可查看历史消息</p> : <><div className='mb-2 flex gap-2 overflow-x-auto no-scrollbar'>{QUICK_REPLIES.map((text) => <button key={text} onClick={() => setInput(text)} className='shrink-0 rounded-full border border-white/10 bg-white/[.04] px-3 py-1.5 text-xs text-white/65'>{text}</button>)}</div><div className='flex min-h-12 items-center gap-2 rounded-2xl border border-white/12 bg-stage-800 px-2'><button aria-label='添加内容' className='h-9 w-8 text-xl text-white/55'>＋</button><input ref={inputRef} value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') send() }} placeholder='输入消息……' className='h-11 min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-white/30'/><button onClick={icebreaker} className='h-9 shrink-0 px-1 text-xs text-violet-400'><MusicIcon className='mr-1 inline h-3.5 w-3.5'/>AI破冰</button><button disabled={!input.trim()} onClick={send} className='h-9 shrink-0 rounded-xl bg-brand-500 px-3 text-sm font-semibold text-stage-950 disabled:opacity-40'>发送</button></div></>}</div> : <p className='py-3 text-center text-sm text-white/55'>等待全部成员确认，确认完成后开放临时群聊。</p>

  return <PageShell title='同频临时房间' subtitle={`${room.members.length} 人小组 · 活动结束 24 小时后自动归档`} step={3} onBack={() => navigate(`/concert/${concertId}/matches`)} right={<DemoBadge/>} footer={footer} footerFixed><div className='flex flex-col gap-4 pb-4'>
    <Card className='border-brand-500/30 bg-brand-500/[0.07]'><SectionTitle title='双向确认状态' hint={`已有 ${confirmedCount} / ${room.members.length} 人确认同行`} icon={<UsersIcon className='h-4 w-4 text-brand-300'/>}/><div className='space-y-2'>{room.members.map((m) => <div key={m.userId} className='flex items-center gap-3 rounded-2xl border border-white/8 bg-white/[.02] px-3 py-2.5'>{m.isMe ? <UserAvatar size={36}/> : <Avatar name={m.nickname} from={m.avatar.from} to={m.avatar.to} size={36}/>}<div className='min-w-0 flex-1'><p className='truncate text-sm text-white/90'>{m.isMe ? profile.nickname : m.nickname}{m.isMe ? '（我）' : ''}</p><p className='truncate text-xs text-white/45'>{m.note}</p></div>{m.confirmed ? <span className='text-xs text-brand-300'>✓ 已确认</span> : <Button size='sm' variant='secondary' onClick={() => toggleMemberConfirm(m.userId)}>确认</Button>}</div>)}</div></Card>
    {!allConfirmed ? <Card className='border-warm-400/25 bg-warm-400/[.05]'><p className='text-sm text-warm-400'>等待全部成员确认，确认完成后开放临时群聊。</p><p className='mt-2 text-xs text-white/45'>Agent 预沟通只交换匿名结构化条件；真人群聊不会提前开放。</p></Card> : <section><SectionTitle title='真人临时群聊' hint='Agent 已退出沟通，以下消息均由真人发送' icon={<UsersIcon className='h-4 w-4 text-brand-400'/>}/><Card className='overflow-hidden p-0'><div className='border-b border-brand-500/20 bg-brand-500/[.06] p-3'><div className='flex gap-2'><MapPinIcon className='mt-0.5 h-4 w-4 shrink-0 text-brand-400'/><div><p className='text-xs font-semibold text-brand-300'>置顶 · 公开集合点</p><p className='mt-1 text-sm text-white'>{room.meetingPoint.name}</p><p className='mt-1 text-xs text-white/50'><ClockIcon className='mr-1 inline h-3 w-3'/>{room.meetingPoint.time} · {room.meetingPoint.note}</p>{room.meetingConfirmed ? <p className='mt-2 text-xs text-brand-300'>✓ 我已记下集合点</p> : <Button size='sm' variant='secondary' className='mt-2' onClick={confirmMeeting}>我已记下集合点</Button>}</div></div></div><div className='max-h-[430px] min-h-[320px] space-y-4 overflow-y-auto p-3' aria-label='临时群聊消息'>{visibleMessages.map((m) => m.system ? <div key={m.id} className='rounded-xl border border-warm-400/20 bg-warm-400/[.06] p-3 text-xs leading-relaxed text-warm-400'><ShieldIcon className='mr-1 inline h-3.5 w-3.5'/>{m.text}</div> : <div key={m.id} className={`flex gap-2 ${m.mine ? 'flex-row-reverse' : ''}`}>{m.mine ? <UserAvatar size={32}/> : <Avatar name={m.nickname} from={m.userId === 'mock-muna' ? '#31f58a' : '#4a7dff'} to='#171a22' size={32}/>}<div className={`max-w-[78%] ${m.mine ? 'text-right' : ''}`}><div className='mb-1 flex gap-2 text-xs text-white/35'><span>{m.mine ? profile.nickname : m.nickname}</span><span>{m.time}</span></div><div className={`rounded-2xl px-3 py-2.5 text-left text-sm leading-relaxed ${m.mine ? 'rounded-tr-sm bg-brand-500 text-stage-950' : 'rounded-tl-sm bg-white/[.07] text-white/85'}`}>{m.text}</div>{!m.mine && <div className='mt-1 flex gap-3 text-xs text-white/30'><button onClick={() => setReportMessage(m)}>举报消息</button><button onClick={() => { setBlocked((prev) => [...prev, m.userId]); pushToast(`已屏蔽 ${m.nickname}`) }}>屏蔽成员</button></div>}</div></div>)}</div></Card></section>}
    <section><button onClick={() => setTasksOpen((v) => !v)} className='flex min-h-12 w-full items-center justify-between rounded-2xl border border-white/10 bg-white/[.025] px-4 text-left'><span><span className='block text-sm font-semibold text-white'>候场任务</span><span className='text-xs text-white/40'>已完成 {doneCount} / {tasks.length}</span></span><span className='text-white/45'>{tasksOpen ? '收起' : '展开'}</span></button>{tasksOpen ? <Card className='mt-2 p-0'>{tasks.map((t) => <button key={t.id} onClick={() => toggleTask(t.id)} className='flex w-full gap-3 border-b border-white/6 px-4 py-3 text-left last:border-0'><span className={`mt-0.5 flex h-5 w-5 items-center justify-center rounded border ${t.done ? 'border-brand-400 bg-brand-500 text-stage-950' : 'border-white/20'}`}><CheckIcon className='h-3 w-3'/></span><span><span className='block text-sm text-white/85'>{t.label}</span><span className='text-xs text-white/40'>{t.detail}</span></span></button>)}</Card> : null}</section>
    <div className='grid grid-cols-2 gap-2'><Button variant='secondary' onClick={() => setExitOpen(true)}>退出房间</Button><Button variant='secondary' onClick={() => setReportMessage(messages.find((m) => !m.system && !m.mine) || null)} icon={<AlertIcon className='h-4 w-4'/>}>举报</Button></div><p className='rounded-2xl border border-white/8 bg-white/[.02] p-3 text-xs leading-relaxed text-white/45'>Agent 预沟通只交换匿名结构化条件；真人群聊仅在全部成员确认后开放。活动结束 24 小时后自动归档。</p>
  </div><Sheet open={exitOpen} onClose={() => setExitOpen(false)} title='要退出这个房间吗？'><Button variant='danger' full onClick={() => { localStorage.removeItem(storageKey); leaveRoom(); navigate('/') }}>确认退出</Button></Sheet><Sheet open={Boolean(reportMessage)} onClose={() => setReportMessage(null)} title='举报单条消息' description={reportMessage ? `来自 ${reportMessage.nickname}：${reportMessage.text}` : ''}><div className='space-y-2'>{REPORT_REASONS.map((r) => <button key={r} onClick={() => setReportReason(r)} className={`w-full rounded-xl border p-3 text-left text-sm ${reportReason === r ? 'border-rose-400/50 bg-rose-400/10' : 'border-white/10'}`}>{r}</button>)}<Button variant='danger' full disabled={!reportReason} onClick={() => { void report(reportReason, reportMessage?.userId || null); setReportMessage(null); setReportReason('') }}>提交举报</Button></div></Sheet></PageShell>
}
